enum STATUS {
  TO_DO = 'TO DO',
  IN_PROGRESS = 'IN PROGRESS',
  DONE = 'DONE',
}

enum ROLE {
  DEVELOPER = 'DEVELOPER',
  DESIGNER = 'DESIGNER',
  MANAGER = 'MANAGER',
}

enum PROJECT {
  NIKE_SNEAKER = 'NIKE SNEAKER',
  NETFLIX = 'NETFLIX',
  LIBRA = 'LIBRA',
}
export { STATUS, ROLE, PROJECT };
