module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleDirectories: ['node_modules'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|svg|css)$': '<rootDir>/fileMock.ts',
    '^@/(.*)': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.ts?$': 'ts-jest',
    '^.+\\.js$': 'babel-jest',
  },
  testPathIgnorePatterns: ['<rootDir>/node_modules/'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/icons/**',
    '!**/types/**',
    '!**/themes/**',
    '!src/main.tsx',
    '!src/helpers/testUtils.tsx',
    '!src/routers/**',
    '!**/mocks/**',
    '!**/Skeleton/**',
    '!**/*.config.ts',
    '!**/node_modules/**',
    '!**/constants/**',
    '!src/layouts/index.tsx',
    '!src/pages/index.ts',
    '!src/vite-env.d.ts',
  ],
};
